### ISSUE TITLE
Fix links in navbar

### ISSUE THREAD

**Issue by jacobhq** [Jacob-Marshall/notes#1]
This is something that I really need to do, but it's very tedious. When you click a link on the navbar, it treats the link like a file in the repository. Any help would be appreciated.

**Comment by petermorgandev** [comment]
The links needed `https://` in front of the URLs. Below is the fixed code. [Here](https://www.coffeecup.com/help/articles/absolute-vs-relative-pathslinks/) is an article that discusses absolute and relative links that you might find useful.

```html
<a class="nav-item nav-link" href="https://jacob-marshall.github.io/Jacob-Marshall/index.html">Home</a>
<a class="nav-item nav-link" href="https://jacob-marshall.github.io/notes/index.html">Sticky notes</a>
<a class="nav-item nav-link" href="https://jacob-marshall.github.io/document.write/home.html">document.write</a>
<a class="nav-item nav-link" href="https://github.com/jacob-marshall">Github</a>
<a class="nav-item nav-link" href="https://anchor.fm/tech-tree">Tech tree</a>
```

**Comment by jacobhq** [comment]
Thanks so much
